name: Auto PR

on:
  push:
    branches:
      - "**/[0-9]**"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Check for existing PR
        id: pr
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ secrets.PROJECT_AUTOMATION }}

      - name: Lookup reviewers
        id: reviewers
        run: |
          name="neyazb"
          if [[ "${{ github.actor }}" == "neyazb" ]]; then
            name="gaps013"
          fi
          echo "reviewers=$name" >> $GITHUB_OUTPUT

      - name: Lookup branch author
        id: author
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/commits/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: ${{ steps.pr.outputs.number == '' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const base = 'dev';
            const issue_number = parseInt(branch.split('-')[0]);
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });
            const title = issue.data.title;
            const issueBody = issue.data.body || '';
            const body = `fixes #${issue_number}\n\n${issueBody}`;
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: base,
              title: title,
              body: body,
              draft: true,
            })
