name: Reusable PR to Draft

on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token with PR permissions'
        required: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  convert-pr-to-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@0.1.3
        if: github.event.pull_request.draft == false
        with:
          token: ${{ secrets.token }}
