name: Reusable PR to Draft

on:
  workflow_call:
    secrets:
      token: ${{ secrets.PROJECT_AUTOMATION }}
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  convert-pr-to-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        if: github.event.pull_request.draft == false
        with:
          token: ${{ secrets.token }}
